# Used when building external pull requests
# We don't want to publish build artifacts or expose our other caches to possibly untrusted code

name: Build - PR
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 21 ]

    steps:
      - name: Extract current branch name
        shell: bash
        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "branch=${ref////-}" >> $GITHUB_OUTPUT
        id: ref

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Build w/ Gradle Wrapper
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: remotely-build
          path: build/libs/*.jar

  dependency-review:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
